import type { RelationshipType, TechnologyCategory, TechnologyResource, TechnologyType } from '../types/technology.js'

export type SeedTechnology = {
  id: string
  name: string
  slug: string
  description: string
  type: TechnologyType
  category: TechnologyCategory
  ecosystem?: string
  logo?: string
  context?: string
  useCases?: string[]
  relationships?: { type: RelationshipType; targetId: string }[]
  resources?: TechnologyResource[]
}

// Curated seed copy of Aster's existing catalogue. PostgreSQL is the runtime source of truth.
export const seedTechnologies: SeedTechnology[] = [
  {
    id: 'angular',
    name: 'Angular',
    slug: 'angular',
    description: 'A web framework for building applications with TypeScript.',
    context: 'Angular brings routing, forms, dependency injection, and other application tools into one framework.',
    type: 'Framework',
    category: 'Frameworks',
    ecosystem: 'TypeScript',
    useCases: ['Large web applications', 'Enterprise application interfaces', 'Progressive web applications'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'typescript' },
      { type: 'commonly_used_with', targetId: 'playwright' },
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'alternative_to', targetId: 'react' },
      { type: 'alternative_to', targetId: 'vue' },
      { type: 'alternative_to', targetId: 'svelte' },
    ],
    resources: [{ label: 'Angular documentation', url: 'https://angular.dev/overview', type: 'Documentation' }],
  },
  {
    id: 'react',
    name: 'React',
    slug: 'react',
    description: 'A JavaScript library for building user interfaces from components.',
    context: 'React focuses on the interface layer. Teams choose additional tools for routing, data access, and application structure.',
    type: 'Library',
    category: 'Frameworks',
    ecosystem: 'JavaScript',
    useCases: ['Interactive web applications', 'Reusable interface systems', 'Single-page applications', 'Component-based user interfaces'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'typescript' },
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'commonly_used_with', targetId: 'vitest' },
      { type: 'commonly_used_with', targetId: 'playwright' },
      { type: 'alternative_to', targetId: 'vue' },
      { type: 'alternative_to', targetId: 'svelte' },
      { type: 'part_of', targetId: 'javascript' },
      { type: 'related_to', targetId: 'react-native' },
    ],
    resources: [{ label: 'React documentation', url: 'https://react.dev/learn', type: 'Documentation' }],
  },
  {
    id: 'svelte',
    name: 'Svelte',
    slug: 'svelte',
    description: 'A UI framework that shifts much of its work to compile time.',
    context: 'Svelte components are compiled into JavaScript and CSS for the browser; SvelteKit adds application and routing features.',
    type: 'Framework',
    category: 'Frameworks',
    ecosystem: 'JavaScript',
    useCases: ['Interactive web applications', 'Lightweight interfaces', 'Reusable web components'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'javascript' },
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'commonly_used_with', targetId: 'playwright' },
      { type: 'alternative_to', targetId: 'vue' },
    ],
    resources: [{ label: 'Svelte documentation', url: 'https://svelte.dev/docs/svelte/overview', type: 'Documentation' }],
  },
  {
    id: 'vue',
    name: 'Vue',
    slug: 'vue',
    description: 'A progressive framework for building web user interfaces.',
    context: 'Vue can enhance a small part of a page or serve as the foundation for a full application.',
    type: 'Framework',
    category: 'Frameworks',
    ecosystem: 'JavaScript',
    useCases: ['Interactive web interfaces', 'Single-page applications', 'Incrementally enhanced websites'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'javascript' },
      { type: 'commonly_used_with', targetId: 'typescript' },
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'commonly_used_with', targetId: 'vitest' },
    ],
    resources: [{ label: 'Vue guide', url: 'https://vuejs.org/guide/introduction.html', type: 'Documentation' }],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    slug: 'typescript',
    description: 'A typed programming language that builds on JavaScript.',
    context: 'TypeScript checks types during development and emits JavaScript that can run in JavaScript environments.',
    type: 'Programming language',
    category: 'Languages',
    ecosystem: 'JavaScript',
    useCases: ['Safer application code', 'Large JavaScript codebases', 'Shared types between teams'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'javascript' },
      { type: 'commonly_used_with', targetId: 'nodejs' },
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'built_on', targetId: 'javascript' },
    ],
    resources: [{ label: 'TypeScript documentation', url: 'https://www.typescriptlang.org/docs/', type: 'Documentation' }],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    slug: 'javascript',
    description: 'A programming language used to create interactive web experiences and more.',
    context: 'In browsers, JavaScript works with web platform APIs. Runtimes such as Node.js also use it outside the browser.',
    type: 'Programming language',
    category: 'Languages',
    ecosystem: 'Web',
    useCases: ['Interactive websites', 'Web applications', 'Server-side programs', 'Browser extensions', 'Desktop and mobile applications'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'nodejs' },
      { type: 'commonly_used_with', targetId: 'react' },
      { type: 'commonly_used_with', targetId: 'vite' },
    ],
    resources: [{ label: 'JavaScript guide on MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide', type: 'Documentation' }],
  },
  {
    id: 'python',
    name: 'Python',
    slug: 'python',
    description: 'A general-purpose programming language used across many kinds of software.',
    context: 'Python favors readable syntax and a broad standard library, with a large collection of tools for specialized work.',
    type: 'Programming language',
    category: 'Languages',
    ecosystem: 'General purpose',
    useCases: ['Automation and scripting', 'Web services', 'Data analysis', 'Scientific computing'],
    resources: [{ label: 'Python tutorial', url: 'https://docs.python.org/3/tutorial/', type: 'Documentation' }],
  },
  {
    id: 'rust',
    name: 'Rust',
    slug: 'rust',
    description: 'A systems programming language focused on performance and memory safety.',
    context: 'Rust gives programmers low-level control while checking memory-safety rules at compile time.',
    type: 'Programming language',
    category: 'Languages',
    useCases: ['Systems software', 'Command-line tools', 'WebAssembly modules'],
    resources: [{ label: 'The Rust Programming Language', url: 'https://doc.rust-lang.org/stable/book/', type: 'Documentation' }],
  },
  {
    id: 'go',
    name: 'Go',
    slug: 'go',
    description: 'A compiled programming language designed for clear, efficient software.',
    context: 'Go is often used to build networked services and infrastructure tools that can run as compiled binaries.',
    type: 'Programming language',
    category: 'Languages',
    ecosystem: 'Cloud native',
    useCases: ['Network services', 'Command-line tools', 'Cloud infrastructure software'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'docker' },
      { type: 'commonly_used_with', targetId: 'kubernetes' },
      { type: 'commonly_used_with', targetId: 'postgresql' },
    ],
    resources: [{ label: 'Go documentation', url: 'https://go.dev/doc/', type: 'Documentation' }],
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    slug: 'nodejs',
    description: 'A JavaScript runtime built on Chrome’s V8 JavaScript engine.',
    context: 'Node.js provides server-side APIs for JavaScript, including filesystem, networking, and process access.',
    type: 'Runtime',
    category: 'Runtimes',
    ecosystem: 'JavaScript',
    useCases: ['Web servers and APIs', 'Command-line tools', 'Build and development tooling'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'vite' },
      { type: 'commonly_used_with', targetId: 'postgresql' },
    ],
    resources: [{ label: 'Introduction to Node.js', url: 'https://nodejs.org/learn/getting-started/introduction-to-nodejs', type: 'Documentation' }],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    slug: 'postgresql',
    description: 'An open-source relational database with support for SQL and extensible data types.',
    context: 'PostgreSQL organizes data in relational tables and supports transactions, constraints, and complex queries.',
    type: 'Database',
    category: 'Databases',
    ecosystem: 'Relational databases',
    useCases: ['Transactional applications', 'Relational data storage', 'Complex queries and reporting'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'redis' },
      { type: 'commonly_used_with', targetId: 'docker' },
    ],
    resources: [{ label: 'PostgreSQL documentation', url: 'https://www.postgresql.org/docs/current/', type: 'Documentation' }],
  },
  {
    id: 'redis',
    name: 'Redis',
    slug: 'redis',
    description: 'An in-memory data store used as a database, cache, and message broker.',
    context: 'Redis exposes in-memory data structures and operations that applications can use for low-latency data access.',
    type: 'Database',
    category: 'Databases',
    ecosystem: 'In-memory data',
    useCases: ['Caching', 'Queues and messaging', 'Real-time data access'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'docker' },
    ],
    resources: [{ label: 'Redis documentation', url: 'https://redis.io/docs/latest/', type: 'Documentation' }],
  },
  {
    id: 'docker',
    name: 'Docker',
    slug: 'docker',
    description: 'A platform for packaging and running applications in containers.',
    context: 'Container images bundle an application with its runtime requirements so it can run consistently across environments.',
    type: 'Container tool',
    category: 'DevOps',
    ecosystem: 'Containers',
    useCases: ['Reproducible development environments', 'Application packaging', 'Continuous integration'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'kubernetes' },
    ],
    resources: [{ label: 'Get started with Docker', url: 'https://docs.docker.com/get-started/', type: 'Documentation' }],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    slug: 'kubernetes',
    description: 'A system for deploying and managing containerized applications.',
    context: 'Kubernetes coordinates container workloads across a cluster and provides primitives for deployment, networking, and scaling.',
    type: 'Container platform',
    category: 'Infrastructure',
    ecosystem: 'Cloud native',
    useCases: ['Container orchestration', 'Service deployment', 'Workload scaling'],
    relationships: [

    ],
    resources: [{ label: 'Kubernetes concepts', url: 'https://kubernetes.io/docs/concepts/', type: 'Documentation' }],
  },
  {
    id: 'vite',
    name: 'Vite',
    slug: 'vite',
    description: 'A frontend build tool with a fast local development server.',
    context: 'Vite serves source files during development and bundles an application for production.',
    type: 'Build tool',
    category: 'Build Tools',
    ecosystem: 'JavaScript',
    useCases: ['Frontend development servers', 'Production asset builds', 'Framework-based web applications'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'vitest' },
    ],
    resources: [{ label: 'Vite guide', url: 'https://vite.dev/guide/', type: 'Documentation' }],
  },
  {
    id: 'vitest',
    name: 'Vitest',
    slug: 'vitest',
    description: 'A JavaScript testing framework designed to work with Vite projects.',
    context: 'Vitest reuses Vite’s configuration and transformation pipeline to run unit and component tests.',
    type: 'Testing tool',
    category: 'Testing',
    ecosystem: 'Vite, JavaScript',
    useCases: ['Unit tests', 'Component tests', 'Code coverage'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'typescript' },
      { type: 'commonly_used_with', targetId: 'playwright' },
      { type: 'built_on', targetId: 'vite' },
    ],
    resources: [{ label: 'Vitest guide', url: 'https://vitest.dev/guide/', type: 'Documentation' }],
  },
  {
    id: 'playwright',
    name: 'Playwright',
    slug: 'playwright',
    description: 'A browser automation framework for testing web applications.',
    context: 'Playwright drives browsers so teams can verify user flows against rendered applications.',
    type: 'Testing tool',
    category: 'Testing',
    ecosystem: 'Browser automation',
    useCases: ['End-to-end browser tests', 'Cross-browser testing', 'Automated browser workflows'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'vite' },
    ],
    resources: [{ label: 'Playwright documentation', url: 'https://playwright.dev/docs/intro', type: 'Documentation' }],
  },
  {
    id: 'react-native',
    name: 'React Native',
    slug: 'react-native',
    description: 'A framework for building native mobile applications with React and JavaScript.',
    context: 'React Native uses React concepts to build native interfaces for mobile platforms.',
    type: 'Framework',
    category: 'Frameworks',
    ecosystem: 'JavaScript',
    useCases: ['Cross-platform mobile applications', 'Native mobile interfaces'],
    relationships: [
      { type: 'commonly_used_with', targetId: 'typescript' },
    ],
    resources: [{ label: 'React Native documentation', url: 'https://reactnative.dev/docs/getting-started', type: 'Documentation' }],
  },
  {
    id: 'microsoft-extensions-dependency-injection',
    name: 'Microsoft.Extensions.DependencyInjection',
    slug: 'microsoft-extensions-dependency-injection',
    description: 'A dependency injection container abstraction and default implementation for .NET applications, commonly used to register and resolve application services.',
    context: 'The .NET service container connects application components while keeping their dependencies explicit.',
    type: 'Library',
    category: 'Libraries',
    ecosystem: '.NET',
  },
]
